@startuml
title ASMP Change Flow

Application->Server: Change Request
note over Server
	components: [
	  callback: <callback endpoint>
	  {
	    name: "php",
	    value: "7.2.13"
	  },
	  {
	    name: "mysql",
	    value: "5.6"
	  }
	]
end note
Server->Application: Change Request Response

Server->Application: Callback
note over Application
	components: [
	  rollbackId: <uuid>
	  {
	    name: "php",
	    value: "7.2.13"
	  },
	  {
	    name: "mysql",
	    value: "5.6"
	  }
	]
end note
@enduml
